steps:
  # Deploy to Kubernetes only if there are changes in the Kubernetes configuration
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'pre-test-deploy.yaml']
    id: Deploy to Kubernetes
    waitFor: ['-']
    includedFiles:
      - 'pre-test-deploy.yaml'

  # Build the pre-test-server image only if there are changes in the server code
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/pre-test/pre-test-server:$SHORT_SHA', 'code/backend/server']
    id: Build pre-test-server
    waitFor: ['-']
    includedFiles:
      - 'code/backend/server/**'

  # Build the pre-test-generator image only if there are changes in the generator code
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/pre-test/pre-test-generator:$SHORT_SHA', 'code/backend/generator']
    id: Build pre-test-generator
    waitFor: ['-']
    includedFiles:
      - 'code/backend/generator/**'

  # Build the pre-test-web-server image only if there are changes in the frontend code
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/pre-test/pre-test-web-server:$SHORT_SHA', 'code/frontend']
    id: Build pre-test-web-server
    waitFor: ['-']
    includedFiles:
      - 'code/frontend/**'

  # Push the pre-test-server image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/pre-test/pre-test-server:$SHORT_SHA']
    id: Push pre-test-server
    waitFor: ['Build pre-test-server']

  # Push the pre-test-generator image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/pre-test/pre-test-generator:$SHORT_SHA']
    id: Push pre-test-generator
    waitFor: ['Build pre-test-generator']

  # Push the pre-test-web-server image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/pre-test/pre-test-web-server:$SHORT_SHA']
    id: Push pre-test-web-server
    waitFor: ['Build pre-test-web-server']

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'
substitutions:
  _SHORT_SHA: 'SHORT_SHA'
