steps:
  # Build the pre-test-web-server image only if there are changes in the frontend code
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/$PROJECT_ID/pre-test/pre-test-web-server:$SHORT_SHA', 'code/frontend']
    id: Build pre-test-web-server

  # Push the pre-test-web-server image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/$PROJECT_ID/pre-test/pre-test-web-server:$SHORT_SHA']
    id: Push pre-test-web-server
    waitFor: ['Build pre-test-web-server']

options:
  logging: CLOUD_LOGGING_ONLY
