version: '3.9'

services:

  pre-test-server:
    build: ./code/backend/server
    environment:
      DB_PASSWORD: test
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mariadb

  pre-test-generator:
    build: ./code/backend/generator
    environment:
      BACKEND_SERVER_ENDPOINT: http://pre-test-server:8080
      REQUESTS_PER_SECOND: 100
    ports:
      - "8081:8080"
    networks:
      - app-network

  mariadb:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: pretest
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 300M
    ports:
      - "9000:80"
    networks:
      - app-network
  
  nginx:
    image: nginx:1.27
    volumes:
      - ./code/frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./code/frontend/html:/usr/share/nginx/html
    ports:
      - "80:8080"

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: