version: '3.9'

services:

  go:
    image: golang:1.21
    volumes:
      - ./code:/go/src/app
    ports:
      - "8080:8080"
    working_dir: /go/src/app
    command: tail -f /dev/null
    networks:
      - app-network

  mariadb:
    image: mariadb:10.4
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: pretest
      MARIADB_USER: test
      MARIADB_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 300M
    ports:
      - "9000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: